version: '3.9'

services:
  db:
    image: postgres
    env_file:
      - ./htmx_websockets/.env
  web:
    build:
      context: .
    command: python3 manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - .:/code
    depends_on:
      db:
        condition: service_started